
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.3
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.3",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.FormScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  published: 'published',
  name: 'name',
  page: 'page',
  components: 'components',
  description: 'description',
  context: 'context',
  visit: 'visit',
  submission: 'submission',
  sharedURL: 'sharedURL',
  currentVersion: 'currentVersion',
  eventConfig: 'eventConfig',
  scheduleType: 'scheduleType',
  scheduleInterval: 'scheduleInterval',
  scheduleConfig: 'scheduleConfig',
  assignedUserId: 'assignedUserId',
  roleId: 'roleId',
  submoduleId: 'submoduleId',
  templateId: 'templateId',
  templateVersion: 'templateVersion'
};

exports.Prisma.FormSubmissionScalarFieldEnum = {
  id: 'id',
  published: 'published',
  formId: 'formId',
  formVersionId: 'formVersionId',
  version: 'version',
  userId: 'userId',
  roleId: 'roleId',
  submoduleId: 'submoduleId',
  content: 'content',
  computedContent: 'computedContent',
  submittedAt: 'submittedAt'
};

exports.Prisma.FormVersionScalarFieldEnum = {
  id: 'id',
  formId: 'formId',
  version: 'version',
  name: 'name',
  description: 'description',
  page: 'page',
  components: 'components',
  context: 'context',
  eventConfig: 'eventConfig',
  scheduleType: 'scheduleType',
  scheduleInterval: 'scheduleInterval',
  scheduleConfig: 'scheduleConfig',
  published: 'published',
  createdAt: 'createdAt'
};

exports.Prisma.FormSubmissionValueScalarFieldEnum = {
  id: 'id',
  submissionId: 'submissionId',
  formId: 'formId',
  formVersionId: 'formVersionId',
  fieldKey: 'fieldKey',
  fieldLabel: 'fieldLabel',
  elementId: 'elementId',
  pageId: 'pageId',
  parentId: 'parentId',
  valueType: 'valueType',
  stringValue: 'stringValue',
  numberValue: 'numberValue',
  booleanValue: 'booleanValue',
  dateValue: 'dateValue',
  jsonValue: 'jsonValue',
  rawValue: 'rawValue',
  createdAt: 'createdAt'
};

exports.Prisma.FormEventScalarFieldEnum = {
  id: 'id',
  formId: 'formId',
  version: 'version',
  name: 'name',
  sourceField: 'sourceField',
  targetField: 'targetField',
  expression: 'expression',
  trigger: 'trigger',
  enabled: 'enabled',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormAssignmentScalarFieldEnum = {
  id: 'id',
  formId: 'formId',
  userId: 'userId',
  roleId: 'roleId',
  submoduleId: 'submoduleId',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SubmoduleScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  description: 'description',
  icon: 'icon',
  metadata: 'metadata',
  baseTables: 'baseTables',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormTemplateScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  description: 'description',
  icon: 'icon',
  metadata: 'metadata',
  page: 'page',
  components: 'components',
  context: 'context',
  eventConfig: 'eventConfig',
  scheduleType: 'scheduleType',
  scheduleInterval: 'scheduleInterval',
  scheduleConfig: 'scheduleConfig',
  currentVersion: 'currentVersion',
  active: 'active',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.FormTemplateVersionScalarFieldEnum = {
  id: 'id',
  templateId: 'templateId',
  version: 'version',
  name: 'name',
  description: 'description',
  icon: 'icon',
  metadata: 'metadata',
  page: 'page',
  components: 'components',
  context: 'context',
  eventConfig: 'eventConfig',
  scheduleType: 'scheduleType',
  scheduleInterval: 'scheduleInterval',
  scheduleConfig: 'scheduleConfig',
  createdAt: 'createdAt'
};

exports.Prisma.RoleScalarFieldEnum = {
  id: 'id',
  key: 'key',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AppUserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  roleId: 'roleId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  Form: 'Form',
  FormSubmission: 'FormSubmission',
  FormVersion: 'FormVersion',
  FormSubmissionValue: 'FormSubmissionValue',
  FormEvent: 'FormEvent',
  FormAssignment: 'FormAssignment',
  Submodule: 'Submodule',
  FormTemplate: 'FormTemplate',
  FormTemplateVersion: 'FormTemplateVersion',
  Role: 'Role',
  AppUser: 'AppUser'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
